[tool.poetry]
name = "oop-hw-14-1"
version = "0.1.0"
description = ""
authors = ["Mihouk <arbi_14@mail.ru>"]
readme = "README.md"
packages = [{include = "oop_hw_14"}]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
